name:
wandb:
  offline: false
  name: MODEL-NAME_${now:%Y-%m-%d}_${now:%H-%M-%S}
trainer:
  dataset_path:
    train: 
    test: 
  batch_size:
    train: 
    eval: 
    test: 
model:
  optimizer:
  lr:
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
